### ISSUE TITLE
launch the rapydo command from any subdir of the project

### ISSUE THREAD

**Issue by pdonorio** [rapydo/issues#103]
It seems a commodity wanted feature.

It could be possible:
- we check the dir content for `projects` and `submodules`. if not there we go upwards
- if we reach the root over, failed
- otherwise we cwd with python into the right dir and do rapydo things

what do you think @mdantonio ?

**Comment by mdantonio** [comment]
Absolutely not a priority for me, but I admit that it would be convenient

**Comment by mdantonio** [comment]
I tried to give a change to this issue but found a problem.

the tested algorith is the following:

inspect the current folder: if not good, go one level up (`os.chdir('..')`) and inspect again
Repeat until the root is reached or after a number of iteration (just to avoid infinite iterations in case of problems)

If all inspected levels give error, exit with the error from the original level (the first one)

This algorith fails when you are inside a folder linked by a symbolic link, i.e. in submodules:

I'm here:

`/myroot/myproject/submodules/utils`

but utils is a link to `/myroot/rapydo/utils`

`os.chdir("..")` does not bring me in `/myroot/myproject/submodules/` but in `/myroot/rapydo/` so i will never reach `/myroot/myproject `

**Comment by mdantonio** [comment]
I pushed the described algorithm, it works if the current path does not contain symbolic links, otherwise it will be fooled as described

I don't know how to fix this problem, feel free to complete the implementation if you have a idea, undo it or close the issue by keeping this partially working version

**Comment by pdonorio** [comment]
What if as fix for that problem we simply check the path before inspecting with chdir:
if it contains submodules than the root is the dir before it.

I think I have links only in that folder.
Let me know.

**Comment by mdantonio** [comment]
I don't think that this will work. Python resolves the path by following the linked resource. If you find a way to obtain the right path then we can walk on it

**Comment by pdonorio** [comment]
I think that path has to be something like:
`/my/path/to/the/project/called/paolo/submodules/link`

If you keep the original absolute path string
and cd into the subdir reversely removing the last dir in the string 
you can do:

1. `/my/path/to/the/project/called/paolo/submodules/link`
2. `/my/path/to/the/project/called/paolo/submodules/`
3. `/my/path/to/the/project/called/paolo`<- you find here `projects` and it is the root

What do you think?

**Comment by mdantonio** [comment]
I think that this will not work because "Python resolves the path by following the linked resource."

An example to explain better the issue (yesterday i was driving and so unable to write a lot)

If you are in `/my/path/to/the/project/called/paolo/submodules/link
`
and link is a symlink pointing to `/my/path/to/the/components/mysubmodule`

Python is unable to understand that you are in `/my/path/to/the/project/called/paolo/submodules/link` but is fooled and think that you are in the real path `/my/path/to/the/components/mysubmodule`

All python commands: `os.chdir('..')`, `os.getcwd()` are based on the second path (the real one on the filesystem) and not the first (what we desire).

`os.chdir('..')` or walk along the getcwd path is the same: you are working on the wrong path and you will never reach your project folder


A practical example:

```
$ mkdir -p /my/path/to/the/project/called/paolo/submodules/

$ mkdir -p /my/path/to/the/components/mysubmodule

$ cd /my/path/to/the/project/called/paolo/submodules/

$ ln -s /my/path/to/the/components/mysubmodule link

$ ls -l /my/path/to/the/project/called/paolo/submodules/link
lrwxrwxrwx 1 root root 38 ago  3 07:57 /my/path/to/the/project/called/paolo/submodules/link -> /my/path/to/the/components/mysubmodule

$ cd /my/path/to/the/project/called/paolo/submodules/link

$ pwd
/my/path/to/the/project/called/paolo/submodules/link

$ python3

>>> import os

>>> os.getcwd()
'/my/path/to/the/components/mysubmodule'

>>> os.chdir('..')
>>> os.getcwd()
'/my/path/to/the/components'
>>> 

```

So, how to obtain the desidered path??

The only solution that I'm able to see is obtain the current path with bash instead of python

```
$ pwd
/my/path/to/the/project/called/paolo/submodules/link

$ python3

>>> import os

>>> os.getcwd()
'/my/path/to/the/components/mysubmodule'

>>> os.system('pwd')
/my/path/to/the/project/called/paolo/submodules/link
0
```

or read the PWD env variable:

```
>>> os.environ['PWD']
'/my/path/to/the/project/called/paolo/submodules/link'
```

But both solutions strongly leverage on OS (although they should work on every unix distro)

**Comment by mdantonio** [comment]
Running rapydo from outside the main folder works, but .projectrc file is ignored
