### ISSUE TITLE
Registration not working from swagger UI

### ISSUE THREAD

**Issue by pdonorio** [rapydo/issues#119]
Using swagger and the `custom_parameters: Users` instead of the previous `parameters` (still there commented) ends up with 

```
...
  "errors": [
      "Empty input"
```

like you are sending input via query instead of via body JSON

**Comment by pdonorio** [comment]
There was a bug when I opened the issue,
where if you tried to register with `POST` on `/api/profile` using the Swagger UI 
the parameters were not received.

This might be do on not using [this](https://github.com/rapydo/http-api/blob/0.6.3/restapi/swagger/profile/post.yaml#L13-L17) anymore, but instead the custom parameters option.

But I don't have time to check again and look into it and fix it now.

**Comment by mdantonio** [comment]
I tried to have a look at our swagger.py converter and indeed we only support [custom_parameters ](https://github.com/rapydo/http-api/blob/a127fbd38df938814f4ae53aa68847cbb2113bc7/restapi/swagger.py#L139) and [path parameters](https://github.com/rapydo/http-api/blob/a127fbd38df938814f4ae53aa68847cbb2113bc7/restapi/swagger.py#L156)

Body parameters seems to be not directly supported and this matches with what you reported here.

But since we can use custom_parameters and there is very limited effort here and no specific use case requiring this improvement, i think that we can close the issue
