### ISSUE TITLE
Security checks

### ISSUE THREAD

**Issue by pdonorio** [rapydo/issues#32]
We could start from https://github.com/ant4g0nist/Susanoo

**Comment by pdonorio** [comment]
Also for CORS configuration: http://web-in-security.blogspot.it/2017/07/cors-misconfigurations-on-large-scale.html

**Comment by mdantonio** [comment]
Following the link for CORS configuration i tested the cors script and found the Origin reflection vulnarability

/api/status - Warning: Access-Control-Allow-Origin dynamically generated
/api/status - Alert: Origin reflection

Origin reflection = The origin is simply echoed in ACAO header, any site is allowed to access the resource

Since we really want to make APIs accessible from anyone, is that a problem? 

And more in general: what do we want to do with CORS?

**Comment by mdantonio** [comment]
(i tried to test Susanoo... but after several problems I give up)

**Comment by pdonorio** [comment]
This is important but we don't have any effort for such a complicated and long issue
