### ISSUE TITLE
Health check containers and restart policy

### ISSUE THREAD

**Issue by pdonorio** [rapydo/issues#58]
Should containers restart automatically when they crash?

Should we add health check commands to containers (at least backend)? If yes:
https://sreeninet.wordpress.com/2017/08/15/docker-features-for-handling-containers-death-and-resurrection/

**Comment by mdantonio** [comment]
> Should containers restart automatically when they crash?

I waited some days before to give a response to this question because I'm pretty undecided...

Could be useful, but also very dangerous... It strongly depends from case to case and it is difficult to automatically understand in the case is safe enough to restart the container without any manual intervention

So i think: no, container should not restart automatically.

BUT: if we add a configuration at container level to specifiy if the specific container can be safely automatically restarted (default=False), then the question totally changes

```
neo4j:
    autorestart: False
celery:
    autorestart: True
```

> Should we add health check commands to containers (at least backend)?

An healthy check could be always useful, also without auto-restart

However some containers can be simply checked from outside (e.g. uptime robot) and the healthy is not particullary useful. But containers not directly exposed (e.g. celery) cannot be checked from outside

Overall this issue is very interesting, but with a low priority for me

**Comment by pdonorio** [comment]
> we add a configuration at container level to specifiy if the container can be safely automatically restarted (default=False)

Perfect!

> containers not directly exposed (e.g. celery) cannot be checked from outside

We are starting to prepare a first real internal container environment in Seadata, while also Eudat and all other projects are demanding more and more on this subject.

I personally think we will go through `kubernetes` in a way or another (hopefully with `rancher`). Luckily these tools have much more skills on handling "healthiness" of isolated containers

> Overall this issue is very interesting, but with a low priority for me

This might have a bigger priority for me since we are now in a release candidate and closer to production. And one thing you want there is to restart the backend container at the very least if for some unknown reason `uwsgi` and/or `nginx` crashes

A final note: healthiness in our context is a strange concept. For example we may have a mechanism of authentication with B2STAGE linked to B2ACCESS or B2SAFE; the services are all up but the authentication mechanism does not work, for some reason. This means that also that authentication needs some periodic health check (e.g. testing username/pw against).

**Comment by pdonorio** [comment]
More info about the "healthcheck" command: 
https://medium.com/devopslinks/d-ealer-auto-healing-docker-containers-using-python-docker-api-ce6d5269dcd1

**Comment by pdonorio** [comment]
This is important for the `cluster of containers` point of view.
Should be a follow up to #9

**Comment by mdantonio** [comment]
Added some restart policies to common services. Investigate the healtcheck command remains a critical task, but can be done together with cluster mode #9

**Comment by mdantonio** [comment]
Restart policies to common services work well. What is still missing (mainly healtchecks) will be delayed when (if) the cluster mode will be introduced

**Comment by mdantonio** [comment]
health checks introduced in v2.0
